//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCHEBNAYAPRAKTIKA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LogIn
    {
        public System.Guid UserKey { get; set; }
        [Required]
        public string Login1 { get; set; }
        [Required]
        public string Password { get; set; }

        public System.Guid TypeKey { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
