//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCHEBNAYAPRAKTIKA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Zakupka
    {
        public System.Guid ZakupkaKey { get; set; }

        [Required]
        public string WorkTitle { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:C}")]
        [Range(0, 999999999.99)]
        public decimal ContractSum { get; set; }

        [Required]
        [DisplayFormat(DataFormatString = "{0:C}")]
        [Range(0, 999999999.99)]
        public decimal CashCover { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:D}", ApplyFormatInEditMode = true)]
        public System.DateTime Deadline { get; set; }

        public Nullable<System.Guid> ResponsiblePersonKey { get; set; }
        public Nullable<System.Guid> TimeZoneKey { get; set; }
        public Nullable<System.Guid> AuctionKey { get; set; }
        public Nullable<System.Guid> AdressKey { get; set; }
        public Nullable<System.Guid> StatusKey { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Adress Adress { get; set; }
        public virtual Auction Auction { get; set; }
        public virtual ResponsiblePerson ResponsiblePerson { get; set; }
        public virtual Status Status { get; set; }
        public virtual TimeZone TimeZone { get; set; }
    }
}
